version: "3.8"

services:
  app:
    build: .
    container_name: learning-pipeline
    ports:
      - "8501:8501"
      - "8765:8765"
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    env_file:
      - .env